// Executes the exact declaration probes generated by nr_layout512_dx12.cpp, compiled by DXC.
#include <vulkan/vulkan.h>
#include <filesystem>
#include <fstream>
#include <vector>
#include <array>
#include <iostream>
#include <algorithm>
#include "nr_layout512_expected.h"
static void Check(VkResult r,const char* why) { if(r!=VK_SUCCESS) throw std::runtime_error(std::string(why)+": "+std::to_string(r)); }
static void Require(bool b,const char* why) { if(!b) throw std::runtime_error(why); }
int main(int argc,char** argv) try {
    Require(argc==2,"argument: directory of three compiled declaration probes");
    VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="NR layout-only sentinel";app.apiVersion=VK_API_VERSION_1_1;
    VkInstanceCreateInfo ci{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ci.pApplicationInfo=&app;VkInstance instance;Check(vkCreateInstance(&ci,nullptr,&instance),"instance");
    uint32_t n=0;Check(vkEnumeratePhysicalDevices(instance,&n,nullptr),"devices");Require(n>0,"no Vulkan device");std::vector<VkPhysicalDevice> physicals(n);Check(vkEnumeratePhysicalDevices(instance,&n,physicals.data()),"devices");
    VkPhysicalDevice physical=physicals[0];VkPhysicalDeviceProperties props;vkGetPhysicalDeviceProperties(physical,&props);std::cout<<props.deviceName<<"; validation layer not enabled\n";
    uint32_t familyCount=0;vkGetPhysicalDeviceQueueFamilyProperties(physical,&familyCount,nullptr);std::vector<VkQueueFamilyProperties> families(familyCount);vkGetPhysicalDeviceQueueFamilyProperties(physical,&familyCount,families.data());
    uint32_t family=0;while(family<familyCount && !(families[family].queueFlags&VK_QUEUE_COMPUTE_BIT))++family;Require(family<familyCount,"no compute queue");
    float priority=1;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=family;qi.queueCount=1;qi.pQueuePriorities=&priority;
    VkDeviceCreateInfo di{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};di.queueCreateInfoCount=1;di.pQueueCreateInfos=&qi;VkDevice device;Check(vkCreateDevice(physical,&di,nullptr,&device),"device");VkQueue queue;vkGetDeviceQueue(device,family,0,&queue);
    VkPhysicalDeviceMemoryProperties memoryProperties;vkGetPhysicalDeviceMemoryProperties(physical,&memoryProperties);
    struct Buffer {VkBuffer buffer;VkDeviceMemory memory;void* mapped;};
    const auto createBuffer=[&](VkDeviceSize size,VkBufferUsageFlags usage) {
        Buffer b{};VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=size;bi.usage=usage;Check(vkCreateBuffer(device,&bi,nullptr,&b.buffer),"buffer");VkMemoryRequirements req;vkGetBufferMemoryRequirements(device,b.buffer,&req);
        uint32_t type=0;const auto needed=VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
        while(type<memoryProperties.memoryTypeCount && (!(req.memoryTypeBits&(1u<<type)) || (memoryProperties.memoryTypes[type].propertyFlags&needed)!=needed))++type;Require(type<memoryProperties.memoryTypeCount,"host coherent memory unavailable");
        VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=type;Check(vkAllocateMemory(device,&ai,nullptr,&b.memory),"memory");Check(vkBindBufferMemory(device,b.buffer,b.memory,0),"bind");Check(vkMapMemory(device,b.memory,0,size,0,&b.mapped),"map");return b;
    };
    const VkDeviceSize alignment=std::max<VkDeviceSize>(1,props.limits.minUniformBufferOffsetAlignment);
    const VkDeviceSize stride=(sizeof(DlssNrConstants)+alignment-1)/alignment*alignment;
    auto constants=createBuffer(stride*kSlotCount,VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT);auto output=createBuffer(kWordCount*4,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT);
    std::array<VkDescriptorSetLayoutBinding,2> bindings{};bindings[0]={0,VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,1,VK_SHADER_STAGE_COMPUTE_BIT,nullptr};bindings[1]={7,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1,VK_SHADER_STAGE_COMPUTE_BIT,nullptr};
    VkDescriptorSetLayoutCreateInfo li{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};li.bindingCount=2;li.pBindings=bindings.data();VkDescriptorSetLayout layout;Check(vkCreateDescriptorSetLayout(device,&li,nullptr,&layout),"set layout");
    VkPipelineLayoutCreateInfo pli{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pli.setLayoutCount=1;pli.pSetLayouts=&layout;VkPipelineLayout pipelineLayout;Check(vkCreatePipelineLayout(device,&pli,nullptr,&pipelineLayout),"pipeline layout");
    std::array<VkDescriptorPoolSize,2> sizes{{{VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,kSlotCount},{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,kSlotCount}}};
    VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpi.maxSets=kSlotCount;dpi.poolSizeCount=2;dpi.pPoolSizes=sizes.data();VkDescriptorPool pool;Check(vkCreateDescriptorPool(device,&dpi,nullptr,&pool),"pool");
    std::array<VkDescriptorSetLayout,kSlotCount> layouts;layouts.fill(layout);std::array<VkDescriptorSet,kSlotCount> sets{};VkDescriptorSetAllocateInfo dai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};dai.descriptorPool=pool;dai.descriptorSetCount=kSlotCount;dai.pSetLayouts=layouts.data();Check(vkAllocateDescriptorSets(device,&dai,sets.data()),"sets");
    for(unsigned slot=0;slot<kSlotCount;++slot) {
        VkDescriptorBufferInfo cb{constants.buffer,stride*slot,sizeof(DlssNrConstants)},ob{output.buffer,0,kWordCount*4};
        std::array<VkWriteDescriptorSet,2> writes{};for(auto& w:writes){w.sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;w.dstSet=sets[slot];w.descriptorCount=1;}
        writes[0].dstBinding=0;writes[0].descriptorType=VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;writes[0].pBufferInfo=&cb;writes[1].dstBinding=7;writes[1].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;writes[1].pBufferInfo=&ob;vkUpdateDescriptorSets(device,2,writes.data(),0,nullptr);
    }
    VkCommandPoolCreateInfo cpi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};cpi.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;cpi.queueFamilyIndex=family;VkCommandPool commands;Check(vkCreateCommandPool(device,&cpi,nullptr,&commands),"command pool");
    VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};cai.commandPool=commands;cai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;cai.commandBufferCount=1;VkCommandBuffer cmd;Check(vkAllocateCommandBuffers(device,&cai,&cmd),"commands");
    VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};VkFence fence;Check(vkCreateFence(device,&fi,nullptr,&fence),"fence");
    for(unsigned shader=0;shader<3;++shader) {
        auto file=std::filesystem::path(argv[1])/(std::string(kShaderFiles[shader])+".probe.spv");std::ifstream input(file,std::ios::binary|std::ios::ate);Require(input.good(),"SPIR-V open");const auto bytes=static_cast<size_t>(input.tellg());Require(bytes%4==0 && bytes>0,"SPIR-V length");std::vector<uint32_t> words(bytes/4);input.seekg(0);input.read(reinterpret_cast<char*>(words.data()),bytes);
        VkShaderModuleCreateInfo smi{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};smi.codeSize=bytes;smi.pCode=words.data();VkShaderModule module;Check(vkCreateShaderModule(device,&smi,nullptr,&module),"module");
        VkComputePipelineCreateInfo pi{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};pi.layout=pipelineLayout;pi.stage.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;pi.stage.stage=VK_SHADER_STAGE_COMPUTE_BIT;pi.stage.module=module;pi.stage.pName="LayoutProbe";VkPipeline pipeline;Check(vkCreateComputePipelines(device,VK_NULL_HANDLE,1,&pi,nullptr,&pipeline),"pipeline");
        for(unsigned round=0;round<kRounds;++round) {
            const auto slot=round%kSlotCount;auto values=MakeSentinels(shader,round);std::memcpy(static_cast<char*>(constants.mapped)+stride*slot,&values,sizeof(values));
            Check(vkResetCommandBuffer(cmd,0),"reset command");VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};begin.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;Check(vkBeginCommandBuffer(cmd,&begin),"begin");
            vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,pipeline);vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,pipelineLayout,0,1,&sets[slot],0,nullptr);vkCmdDispatch(cmd,1,1,1);
            VkMemoryBarrier barrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};barrier.srcAccessMask=VK_ACCESS_SHADER_WRITE_BIT;barrier.dstAccessMask=VK_ACCESS_HOST_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_HOST_BIT,0,1,&barrier,0,nullptr,0,nullptr);Check(vkEndCommandBuffer(cmd),"end");
            VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};submit.commandBufferCount=1;submit.pCommandBuffers=&cmd;Check(vkQueueSubmit(queue,1,&submit,fence),"submit");Check(vkWaitForFences(device,1,&fence,VK_TRUE,30000000000ull),"submitted fence completion");
            Require(MatchesSentinels(static_cast<const uint32_t*>(output.mapped),shader,round),"Vulkan sentinel mismatch including offset 256");Check(vkResetFences(device,1,&fence),"reset fence");
        }
        vkDestroyPipeline(device,pipeline,nullptr);vkDestroyShaderModule(device,module,nullptr);std::cout<<"PASS Vulkan "<<kShaderFiles[shader]<<": 65 words x 6 writes / 3 slots, offset 256 readable\n";
    }
    Check(vkDeviceWaitIdle(device),"idle");vkDestroyFence(device,fence,nullptr);vkDestroyCommandPool(device,commands,nullptr);vkDestroyDescriptorPool(device,pool,nullptr);vkDestroyPipelineLayout(device,pipelineLayout,nullptr);vkDestroyDescriptorSetLayout(device,layout,nullptr);
    for(auto* b:{&constants,&output}){vkUnmapMemory(device,b->memory);vkDestroyBuffer(device,b->buffer,nullptr);vkFreeMemory(device,b->memory,nullptr);}vkDestroyDevice(device,nullptr);vkDestroyInstance(instance,nullptr);
    std::cout<<"PASS: 1170 Vulkan sentinel words; submitted-fence completion; no game or NGX runtime\n";return 0;
} catch(const std::exception& e) {std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}
